version: "3"

services:
  lavalink:
    build:
      context: .
      target: lavalink
    networks:
      - lava
    hostname: lavalink
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2333/version"]
      interval: 10s
      timeout: 5s
      retries: 5

  discord_bot:
    build:
      context: .
    env_file:
      - stack.env
    depends_on:
      lavalink:
        condition: service_healthy
    networks:
      - lava

networks:
  lava:
    driver: bridge
