[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerComposeFile = "docker-compose.yml"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
