[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"
dockerComposeFile = "docker-compose.yml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
